apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qqqai.fullname" . }}-secret
  labels:
    {{- include "qqqai.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_QQ: {{ .Values.config.botQQ | quote }}
  LLM_API_KEY: {{ .Values.secrets.llmAPIKey | quote }}
  ARK_KEY: {{ .Values.secrets.arkKey | quote }}
  DEEPSEEK_KEY: {{ .Values.secrets.deepseekKey | quote }}
  QWEN_KEY: {{ .Values.secrets.qwenKey | quote }}
  NAPCAT_ACCESS_TOKEN: {{ .Values.secrets.napcatAccessToken | quote }}
  LANGSMITH_API_KEY: {{ .Values.secrets.langsmithAPIKey | quote }}
  MYSQL_USERNAME: {{ .Values.mysql.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
